export let TRIPS = [
  {
    id: 1,
    name: "ICE",
    price_adult: 60,
    price_child: 30,
    discount: 6,
    discount_vendor: "McDonald's",
    time: "1h 12m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Booking Summary",
    thumb: "assets/img/db_logo.png",
    description: "ICE and the highest class of fast trains by DB, it assures the highest comfort of travel combined with the shortest possible commute time.",
    location: "",
    images: [
    ],
    highlights: [
      "Free WLAN",
      "220v electricity socket",
      "Toilet",
      "Restaurant wagon",
      "Quite wagon",
    ]
  },
  {
    id: 2,
    name: "ICE + EC",
    price_adult: 50,
    price_child: 30,
    discount: 5,
    discount_vendor: "McDonald's",
    time: "2h 23m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Booking Summart",
    thumb: "assets/img/db_logo.png",
    description: "",
    location: "",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "EC",
    price_adult: 30,
    price_child: 15,
    discount: 3,
    discount_vendor: "Starbucks",
    time: "3h 12m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Booking Summart",
    thumb: "assets/img/db_logo.png",
    location: "",
    description: "",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "DB REGIO",
    discount: 2,
    discount_vendor: "Starbucks",
    price_adult: 24,
    price_child: 12,
    time: "5h 46m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Booking Summart",
    thumb: "assets/img/db_logo.png",
    description: "",
    location: "",
    images: [],
    highlights: []
  }
]
