export let TRIPS = [
  {
    id: 1,
    name: "ICE",
    price_adult: 60,
    price_child: 30,
    discount: 6,
    discount_vendor: "McDonald's",
    time: "1h 12m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Booking Summary",
    thumb: "assets/img/db_logo.png",
    description: "ICE and the highest class of fast trains by DB, it assures the highest comfort of travel combined with the shortest possible commute time.",
    // location: "Rio de Janeiro, Brazil",
    images: [
      // "assets/img/trip/thumb/trip_5.jpg",
      // "assets/img/trip/thumb/trip_6.jpg",
      // "assets/img/trip/thumb/trip_7.jpg",
      // "assets/img/trip/thumb/trip_8.jpg",
    ],
    highlights: [
      "Free WLAN",
      "220v electricity socket",
      "Toilet",
      "Restaurant wagon",
      "Quite wagon",
    ]
  },
  {
    id: 2,
    name: "ICE + EC",
    price_adult: 50,
    price_child: 30,
    discount: 5,
    discount_vendor: "McDonald's",
    time: "2h 23m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/db_logo.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "EC",
    price_adult: 30,
    price_child: 15,
    discount: 3,
    discount_vendor: "Starbucks",
    time: "3h 12m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/db_logo.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "São Paulo, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "DB REGIO",
    discount: 2,
    discount_vendor: "Starbucks",
    price_adult: 24,
    price_child: 12,
    time: "5h 46m",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/db_logo.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [],
    highlights: []
  }
]
